// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VictuzAppMVC.Models;

#nullable disable

namespace VictuzAppMVC.Migrations
{
    [DbContext(typeof(VictuzAppContext))]
    [Migration("20241108210525_SyncDatabase")]
    partial class SyncDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActiviteitCategorieKoppeling", b =>
                {
                    b.Property<int>("ActiviteitId")
                        .HasColumnType("int")
                        .HasColumnName("ActiviteitID");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int")
                        .HasColumnName("CategorieID");

                    b.HasKey("ActiviteitId", "CategorieId")
                        .HasName("PK__Activite__CE21AF388DC1EBB2");

                    b.HasIndex("CategorieId");

                    b.ToTable("ActiviteitCategorieKoppeling", (string)null);
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Aanmeldingen", b =>
                {
                    b.Property<int>("AanmeldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AanmeldingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AanmeldingId"));

                    b.Property<DateTime>("AanmeldDatum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ActiviteitId")
                        .HasColumnType("int")
                        .HasColumnName("ActiviteitID");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int")
                        .HasColumnName("GebruikerID");

                    b.HasKey("AanmeldingId")
                        .HasName("PK__Aanmeldi__D705C3B943894FF4");

                    b.HasIndex("ActiviteitId");

                    b.HasIndex(new[] { "GebruikerId", "ActiviteitId" }, "UQ_Gebruiker_Activiteit")
                        .IsUnique();

                    b.ToTable("Aanmeldingen", (string)null);
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Activiteiten", b =>
                {
                    b.Property<int>("ActiviteitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActiviteitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActiviteitId"));

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsVoorstel")
                        .HasColumnType("bit");

                    b.Property<string>("Locatie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxDeelnemers")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActiviteitId")
                        .HasName("PK__Activite__B14595E035BB1C25");

                    b.ToTable("Activiteiten", (string)null);
                });

            modelBuilder.Entity("VictuzAppMVC.Models.EvenementCategorieën", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategorieID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("CategorieNaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategorieId")
                        .HasName("PK__Evenemen__F643AD86180B9053");

                    b.ToTable("EvenementCategorieën", (string)null);
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GebruikerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBestuurslid")
                        .HasColumnType("bit");

                    b.Property<int?>("LidmaatschapId")
                        .HasColumnType("int")
                        .HasColumnName("LidmaatschapID");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GebruikerId")
                        .HasName("PK__Gebruike__4282ABF5F068F3BC");

                    b.HasIndex("LidmaatschapId");

                    b.HasIndex(new[] { "Email" }, "UQ__Gebruike__A9D1053470D9A463")
                        .IsUnique();

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Lidmaatschappen", b =>
                {
                    b.Property<int>("LidmaatschapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LidmaatschapID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LidmaatschapId"));

                    b.Property<string>("Beschrijving")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LidmaatschapId")
                        .HasName("PK__Lidmaats__27325D7CD2D147F7");

                    b.ToTable("Lidmaatschappen", (string)null);
                });

            modelBuilder.Entity("VictuzAppMVC.Models.ViewActiviteitenAanmeldingen", b =>
                {
                    b.Property<int?>("AantalAanmeldingen")
                        .HasColumnType("int");

                    b.Property<int>("ActiviteitId")
                        .HasColumnType("int")
                        .HasColumnName("ActiviteitID");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime");

                    b.Property<int?>("MaxDeelnemers")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("View_ActiviteitenAanmeldingen", (string)null);
                });

            modelBuilder.Entity("ActiviteitCategorieKoppeling", b =>
                {
                    b.HasOne("VictuzAppMVC.Models.Activiteiten", null)
                        .WithMany()
                        .HasForeignKey("ActiviteitId")
                        .IsRequired()
                        .HasConstraintName("FK__Activitei__Activ__412EB0B6");

                    b.HasOne("VictuzAppMVC.Models.EvenementCategorieën", null)
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .IsRequired()
                        .HasConstraintName("FK__Activitei__Categ__4222D4EF");
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Aanmeldingen", b =>
                {
                    b.HasOne("VictuzAppMVC.Models.Activiteiten", "Activiteit")
                        .WithMany("Aanmeldingens")
                        .HasForeignKey("ActiviteitId")
                        .IsRequired()
                        .HasConstraintName("FK__Aanmeldin__Activ__2C3393D0");

                    b.HasOne("VictuzAppMVC.Models.Gebruiker", "Gebruiker")
                        .WithMany("Aanmeldingens")
                        .HasForeignKey("GebruikerId")
                        .IsRequired()
                        .HasConstraintName("FK__Aanmeldin__Gebru__2B3F6F97");

                    b.Navigation("Activiteit");

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Gebruiker", b =>
                {
                    b.HasOne("VictuzAppMVC.Models.Lidmaatschappen", "Lidmaatschap")
                        .WithMany("Gebruikers")
                        .HasForeignKey("LidmaatschapId")
                        .HasConstraintName("FK__Gebruiker__Lidma__44FF419A");

                    b.Navigation("Lidmaatschap");
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Activiteiten", b =>
                {
                    b.Navigation("Aanmeldingens");
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Gebruiker", b =>
                {
                    b.Navigation("Aanmeldingens");
                });

            modelBuilder.Entity("VictuzAppMVC.Models.Lidmaatschappen", b =>
                {
                    b.Navigation("Gebruikers");
                });
#pragma warning restore 612, 618
        }
    }
}
